### ISSUE TITLE
Modify the website

### ISSUE THREAD

**Issue by larissadj** [FabLab-Luenen/McLighting#111]

**Comment by larissadj** [comment]
Hi,
is it possible to modify the website as my need? I need to add 3 buttons on the website for the 3 colors red, blue and white only. In the file index.htm, i modify the title for example and there is no effect on the website. I need to receive on the terminal red when i click this red button on the website.  how can i do please to add  this button on the website or whrere can i modify the website`? On the previous version 2.2.5, the modification of the file index.htm was done. But now no effect...Some issues? Thanks

**Comment by bpohvoodoo** [comment]
First of all you have to comment out the line
#define USE_HTML_MIN_GZ               // uncomment for using index.htm & edit.htm from PROGMEM instead of SPIFFS
to
//#define USE_HTML_MIN_GZ               // uncomment for using index.htm & edit.htm from PROGMEM instead of SPIFFS
in the definitions.h and the recompile and reupload the firmware.

You can modify the index.htm in the data directory on your own, but you have to upload the files
index.htm
apple-touch-icon.png
edit.htm.gz
favicon.ico.gz
material.woff2
of that folder to the Spiffs.
This is done via:
http://your_device_ip/upload
for each of the mentioned files.

**Comment by larissadj** [comment]
My definition.h looks so //#define USE_HTML_MIN_GZ 
i uploaded one by one the above files, because i can choose only one file by upload. At the end, i entered 
http://your_device_ip and my result is the same despite the modification in the index.htm
![output](https://user-images.githubusercontent.com/45171627/100329951-9f75d480-2fce-11eb-81ec-444a93f16011.PNG)

I try also to modify the index.htm after upload via http://ip-address/edit and i clicked on save. but no effects
