### ISSUE TITLE
HTTP Rest API V3?

### ISSUE THREAD

**Issue by ryancasler** [FabLab-Luenen/McLighting#40]
Noticed that there was a new version of the HTTP Rest API in the wiki.  Does that mean that the commands have changed again?  I noticed that /all is no longer listed.  Did that change back to set_mode?

**Comment by bpohvoodoo** [comment]
Yes the all command ist replace by /set?m=0 which was the same.
The /set_mode and all other set_* commands are replaced by set, because they didn't made sense.
Now they are the commands:
/config to manipulate all hole strip and esp specific settings.
/set to manipulate all segment specific settings.

**Comment by ryancasler** [comment]
okay.  But you can still set multiple parameters in one request, correct?  So, currently I am using:

http://192.168.1.142/all?m=15&rgb=FF0000&rgb2=000000&s=180&c=100

I would just change "/all" to "/set" and leave the rest as is?

**Comment by bpohvoodoo** [comment]
Yes.

**Comment by ryancasler** [comment]
Thanks!
